export const dataSuratKelahiran = [
  {
    id: 1,
    namaTerkait: "Budi Santoso",
    jenisKelaminTerkait: "l",
    tempatTglLahirTerkait: "Jakarta, 1 Januari 2020",
    alamatTerkait: "Jl. Merdeka No. 123, Jakarta",
    namaAyah: "Slamet Santoso",
    jenisKelaminAyah: "l",
    tempatTglLahirAyah: "Surabaya, 15 Februari 1980",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Merdeka No. 123, Jakarta",
    namaIbu: "Siti Aminah",
    jenisKelaminIbu: "p",
    tempatTglLahirIbu: "Bandung, 20 Maret 1982",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Merdeka No. 123, Jakarta",
    status: "diproses",
    noSurat: 12345,
    tanggalPembuatan: new Date("2020-01-02"),
  },
  {
    id: 2,
    namaTerkait: "Andi Pratama",
    jenisKelaminTerkait: "l",
    tempatTglLahirTerkait: "Bandung, 5 Mei 2021",
    alamatTerkait: "Jl. Diponegoro No. 456, Bandung",
    namaAyah: "Dedi Pratama",
    jenisKelaminAyah: "l",
    tempatTglLahirAyah: "Jakarta, 10 April 1985",
    agamaAyah: "Kristen",
    alamatAyah: "Jl. Diponegoro No. 456, Bandung",
    namaIbu: "Maria Christina",
    jenisKelaminIbu: "p",
    tempatTglLahirIbu: "Medan, 25 Juni 1987",
    agamaIbu: "Kristen",
    alamatIbu: "Jl. Diponegoro No. 456, Bandung",
    status: "diterima",
    noSurat: 12346,
    tanggalPembuatan: new Date("2021-05-06"),
  },
  {
    id: 3,
    namaTerkait: "Citra Dewi",
    jenisKelaminTerkait: "p",
    tempatTglLahirTerkait: "Surabaya, 10 Oktober 2019",
    alamatTerkait: "Jl. Pahlawan No. 789, Surabaya",
    namaAyah: "Ahmad Fauzi",
    jenisKelaminAyah: "l",
    tempatTglLahirAyah: "Malang, 30 Juli 1982",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Pahlawan No. 789, Surabaya",
    namaIbu: "Rina Kartika",
    jenisKelaminIbu: "p",
    tempatTglLahirIbu: "Yogyakarta, 15 Agustus 1984",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Pahlawan No. 789, Surabaya",
    status: "ditolak",
    pesanDitolak: "Data tidak valid",
    noSurat: 12347,
    tanggalPembuatan: new Date("2019-10-11"),
  },
];
