import { suratKelahiranSchema } from "@/schemas";
import { skBelumMenikahSchema } from "@/schemas/sk-belum-menikah";
import { skIjinKeramaianSchema } from "@/schemas/sk-ijin-keramaian";
import { skPenghasilanOrangTuaSchema } from "@/schemas/sk-penghasilan-orang-tua";
import { suratKematianSchema } from "@/schemas/surat-kematian";
import z from "zod";

export const dataSuratKelahiran: z.infer<typeof suratKelahiranSchema>[] = [
  {
    namaTerkait: "Ahmad Fathur Rahman",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Jakarta",
    tanggalLahirTerkait: new Date("2024-08-13T09:45:00Z"),
    alamatTerkait: "Jl. Merdeka No. 10, Jakarta",
    namaAyah: "Sutrisno Rahman",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Merdeka No. 10, Jakarta",
    tempatLahirAyah: "Bandung",
    tanggalLahirAyah: new Date("1980-06-15T00:00:00Z"),
    namaIbu: "Fatimah Zahra",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Merdeka No. 10, Jakarta",
    tempatLahirIbu: "Surabaya",
    tanggalLahirIbu: new Date("1982-09-10T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Budi Santoso",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Yogyakarta",
    tanggalLahirTerkait: new Date("2024-07-01T13:30:00Z"),
    alamatTerkait: "Jl. Malioboro No. 25, Yogyakarta",
    namaAyah: "Andi Santoso",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Malioboro No. 25, Yogyakarta",
    tempatLahirAyah: "Sleman",
    tanggalLahirAyah: new Date("1975-02-20T00:00:00Z"),
    namaIbu: "Siti Aminah",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Malioboro No. 25, Yogyakarta",
    tempatLahirIbu: "Bantul",
    tanggalLahirIbu: new Date("1977-08-12T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Cindy Aulia",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Bandung",
    tanggalLahirTerkait: new Date("2024-05-15T08:15:00Z"),
    alamatTerkait: "Jl. Setiabudi No. 89, Bandung",
    namaAyah: "Eko Prasetyo",
    jenisKelaminAyah: "L",
    agamaAyah: "Kristen",
    alamatAyah: "Jl. Setiabudi No. 89, Bandung",
    tempatLahirAyah: "Cimahi",
    tanggalLahirAyah: new Date("1982-03-10T00:00:00Z"),
    namaIbu: "Maria Yuliana",
    jenisKelaminIbu: "P",
    agamaIbu: "Kristen",
    alamatIbu: "Jl. Setiabudi No. 89, Bandung",
    tempatLahirIbu: "Garut",
    tanggalLahirIbu: new Date("1984-11-18T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Dewi Lestari",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Surabaya",
    tanggalLahirTerkait: new Date("2024-03-22T14:50:00Z"),
    alamatTerkait: "Jl. Sudirman No. 45, Surabaya",
    namaAyah: "Slamet Riyadi",
    jenisKelaminAyah: "L",
    agamaAyah: "Hindu",
    alamatAyah: "Jl. Sudirman No. 45, Surabaya",
    tempatLahirAyah: "Malang",
    tanggalLahirAyah: new Date("1979-04-05T00:00:00Z"),
    namaIbu: "Komang Ayu",
    jenisKelaminIbu: "P",
    agamaIbu: "Hindu",
    alamatIbu: "Jl. Sudirman No. 45, Surabaya",
    tempatLahirIbu: "Denpasar",
    tanggalLahirIbu: new Date("1981-06-25T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Rama Wijaya",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Denpasar",
    tanggalLahirTerkait: new Date("2024-02-15T09:20:00Z"),
    alamatTerkait: "Jl. Diponegoro No. 10, Denpasar",
    namaAyah: "Adi Wijaya",
    jenisKelaminAyah: "L",
    agamaAyah: "Buddha",
    alamatAyah: "Jl. Diponegoro No. 10, Denpasar",
    tempatLahirAyah: "Mataram",
    tanggalLahirAyah: new Date("1978-09-12T00:00:00Z"),
    namaIbu: "Sari Dewi",
    jenisKelaminIbu: "P",
    agamaIbu: "Buddha",
    alamatIbu: "Jl. Diponegoro No. 10, Denpasar",
    tempatLahirIbu: "Gianyar",
    tanggalLahirIbu: new Date("1980-12-22T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Agus Prasetyo",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Semarang",
    tanggalLahirTerkait: new Date("2024-07-19T12:45:00Z"),
    alamatTerkait: "Jl. Pandanaran No. 45, Semarang",
    namaAyah: "Bambang Prasetyo",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Pandanaran No. 45, Semarang",
    tempatLahirAyah: "Kudus",
    tanggalLahirAyah: new Date("1975-07-07T00:00:00Z"),
    namaIbu: "Sri Rahayu",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Pandanaran No. 45, Semarang",
    tempatLahirIbu: "Jepara",
    tanggalLahirIbu: new Date("1977-05-14T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Rini Kusuma",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Medan",
    tanggalLahirTerkait: new Date("2024-06-05T16:30:00Z"),
    alamatTerkait: "Jl. Gatot Subroto No. 30, Medan",
    namaAyah: "Hendro Kusuma",
    jenisKelaminAyah: "L",
    agamaAyah: "Kristen",
    alamatAyah: "Jl. Gatot Subroto No. 30, Medan",
    tempatLahirAyah: "Pematangsiantar",
    tanggalLahirAyah: new Date("1983-01-15T00:00:00Z"),
    namaIbu: "Lina Maria",
    jenisKelaminIbu: "P",
    agamaIbu: "Kristen",
    alamatIbu: "Jl. Gatot Subroto No. 30, Medan",
    tempatLahirIbu: "Tebing Tinggi",
    tanggalLahirIbu: new Date("1985-04-20T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Yuni Kartika",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Palembang",
    tanggalLahirTerkait: new Date("2024-05-01T11:00:00Z"),
    alamatTerkait: "Jl. Merdeka No. 15, Palembang",
    namaAyah: "Kurniawan",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Merdeka No. 15, Palembang",
    tempatLahirAyah: "Bengkulu",
    tanggalLahirAyah: new Date("1981-08-30T00:00:00Z"),
    namaIbu: "Indah Sari",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Merdeka No. 15, Palembang",
    tempatLahirIbu: "Lampung",
    tanggalLahirIbu: new Date("1983-11-25T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Firman Saputra",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Makassar",
    tanggalLahirTerkait: new Date("2024-04-10T07:45:00Z"),
    alamatTerkait: "Jl. Pettarani No. 20, Makassar",
    namaAyah: "Zainuddin Saputra",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Pettarani No. 20, Makassar",
    tempatLahirAyah: "Gowa",
    tanggalLahirAyah: new Date("1978-03-05T00:00:00Z"),
    namaIbu: "Aisyah Dewi",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Pettarani No. 20, Makassar",
    tempatLahirIbu: "Parepare",
    tanggalLahirIbu: new Date("1980-07-15T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Ari Prabowo",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Solo",
    tanggalLahirTerkait: new Date("2024-02-25T14:10:00Z"),
    alamatTerkait: "Jl. Slamet Riyadi No. 90, Solo",
    namaAyah: "Budi Prabowo",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Slamet Riyadi No. 90, Solo",
    tempatLahirAyah: "Klaten",
    tanggalLahirAyah: new Date("1977-10-12T00:00:00Z"),
    namaIbu: "Nur Aini",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Slamet Riyadi No. 90, Solo",
    tempatLahirIbu: "Boyolali",
    tanggalLahirIbu: new Date("1980-03-25T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Benny Santoso",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Bekasi",
    tanggalLahirTerkait: new Date("2024-06-10T10:00:00Z"),
    alamatTerkait: "Jl. Raya Kalimalang No. 34, Bekasi",
    namaAyah: "Joko Santoso",
    jenisKelaminAyah: "L",
    agamaAyah: "Kristen",
    alamatAyah: "Jl. Raya Kalimalang No. 34, Bekasi",
    tempatLahirAyah: "Cikarang",
    tanggalLahirAyah: new Date("1982-09-20T00:00:00Z"),
    namaIbu: "Linda Kurniawati",
    jenisKelaminIbu: "P",
    agamaIbu: "Kristen",
    alamatIbu: "Jl. Raya Kalimalang No. 34, Bekasi",
    tempatLahirIbu: "Karawang",
    tanggalLahirIbu: new Date("1984-01-18T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Citra Maharani",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Bandar Lampung",
    tanggalLahirTerkait: new Date("2024-05-30T08:30:00Z"),
    alamatTerkait: "Jl. Raden Intan No. 17, Bandar Lampung",
    namaAyah: "Indra Saputra",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Raden Intan No. 17, Bandar Lampung",
    tempatLahirAyah: "Metro",
    tanggalLahirAyah: new Date("1981-08-05T00:00:00Z"),
    namaIbu: "Rina Maharani",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Raden Intan No. 17, Bandar Lampung",
    tempatLahirIbu: "Pringsewu",
    tanggalLahirIbu: new Date("1983-02-14T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Dwi Lestari",
    jenisKelaminTerkait: "P",
    tempatLahirTerkait: "Samarinda",
    tanggalLahirTerkait: new Date("2024-04-20T07:20:00Z"),
    alamatTerkait: "Jl. A. Yani No. 55, Samarinda",
    namaAyah: "Herman Lestari",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. A. Yani No. 55, Samarinda",
    tempatLahirAyah: "Balikpapan",
    tanggalLahirAyah: new Date("1980-05-17T00:00:00Z"),
    namaIbu: "Siti Marlina",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. A. Yani No. 55, Samarinda",
    tempatLahirIbu: "Bontang",
    tanggalLahirIbu: new Date("1982-11-10T00:00:00Z"),
    status: "DIPROSES",
  },
  {
    namaTerkait: "Eka Susilo",
    jenisKelaminTerkait: "L",
    tempatLahirTerkait: "Padang",
    tanggalLahirTerkait: new Date("2024-01-28T16:00:00Z"),
    alamatTerkait: "Jl. Khatib Sulaiman No. 7, Padang",
    namaAyah: "Firdaus Susilo",
    jenisKelaminAyah: "L",
    agamaAyah: "Islam",
    alamatAyah: "Jl. Khatib Sulaiman No. 7, Padang",
    tempatLahirAyah: "Bukittinggi",
    tanggalLahirAyah: new Date("1979-06-30T00:00:00Z"),
    namaIbu: "Nurhayati",
    jenisKelaminIbu: "P",
    agamaIbu: "Islam",
    alamatIbu: "Jl. Khatib Sulaiman No. 7, Padang",
    tempatLahirIbu: "Pariaman",
    tanggalLahirIbu: new Date("1981-09-22T00:00:00Z"),
    status: "DIPROSES",
  },
];

export const dataSuratKematian: z.infer<typeof suratKematianSchema>[] = [
  {
    namaPemohon: "Ahmad Zulkifli",
    jenisKelaminPemohon: "L",
    noNikPemohon: "3172012345678901",
    alamatPemohon: "Jl. Merpati No. 8, Jakarta",
    hubunganKeluargaPemohon: "Ayah",
    namaTerkait: "Zainul Zulkifli",
    jenisKelaminTerkait: "L",
    noNikTerkait: "3172012345678902",
    alamatTerkait: "Jl. Merpati No. 8, Jakarta",
    tanggal: new Date("2024-06-15T10:30:00Z"),
    penyebab: "Lahir",
    tempat: "RS Mitra Keluarga, Jakarta",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Dewi Santika",
    jenisKelaminPemohon: "P",
    noNikPemohon: "3374012345678903",
    alamatPemohon: "Jl. Siliwangi No. 15, Bandung",
    hubunganKeluargaPemohon: "Ibu",
    namaTerkait: "Putri Santika",
    jenisKelaminTerkait: "P",
    noNikTerkait: "3374012345678904",
    alamatTerkait: "Jl. Siliwangi No. 15, Bandung",
    tanggal: new Date("2024-07-20T14:00:00Z"),
    penyebab: "Lahir",
    tempat: "RS Hasan Sadikin, Bandung",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Siti Fatimah",
    jenisKelaminPemohon: "P",
    noNikPemohon: "3578012345678905",
    alamatPemohon: "Jl. Diponegoro No. 20, Surabaya",
    hubunganKeluargaPemohon: "Ibu",
    namaTerkait: "Rahma Fatimah",
    jenisKelaminTerkait: "P",
    noNikTerkait: "3578012345678906",
    alamatTerkait: "Jl. Diponegoro No. 20, Surabaya",
    tanggal: new Date("2024-05-05T08:15:00Z"),
    penyebab: "Lahir",
    tempat: "RS Dr. Soetomo, Surabaya",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Joko Subagyo",
    jenisKelaminPemohon: "L",
    noNikPemohon: "3375012345678907",
    alamatPemohon: "Jl. Pahlawan No. 3, Semarang",
    hubunganKeluargaPemohon: "Ayah",
    namaTerkait: "Budi Subagyo",
    jenisKelaminTerkait: "L",
    noNikTerkait: "3375012345678908",
    alamatTerkait: "Jl. Pahlawan No. 3, Semarang",
    tanggal: new Date("2024-08-01T09:45:00Z"),
    penyebab: "Lahir",
    tempat: "RS Kariadi, Semarang",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Andi Wijaya",
    jenisKelaminPemohon: "L",
    noNikPemohon: "3279012345678909",
    alamatPemohon: "Jl. Merdeka No. 22, Denpasar",
    hubunganKeluargaPemohon: "Ayah",
    namaTerkait: "Candra Wijaya",
    jenisKelaminTerkait: "L",
    noNikTerkait: "3279012345678910",
    alamatTerkait: "Jl. Merdeka No. 22, Denpasar",
    tanggal: new Date("2024-03-18T12:30:00Z"),
    penyebab: "Lahir",
    tempat: "RS Sanglah, Denpasar",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Rina Suryani",
    jenisKelaminPemohon: "P",
    noNikPemohon: "3273012345678911",
    alamatPemohon: "Jl. Sudirman No. 12, Yogyakarta",
    hubunganKeluargaPemohon: "Ibu",
    namaTerkait: "Sinta Suryani",
    jenisKelaminTerkait: "P",
    noNikTerkait: "3273012345678912",
    alamatTerkait: "Jl. Sudirman No. 12, Yogyakarta",
    tanggal: new Date("2024-04-25T11:00:00Z"),
    penyebab: "Lahir",
    tempat: "RS Bethesda, Yogyakarta",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Agus Setiawan",
    jenisKelaminPemohon: "L",
    noNikPemohon: "3573012345678913",
    alamatPemohon: "Jl. Imam Bonjol No. 40, Malang",
    hubunganKeluargaPemohon: "Ayah",
    namaTerkait: "Wulan Setiawan",
    jenisKelaminTerkait: "P",
    noNikTerkait: "3573012345678914",
    alamatTerkait: "Jl. Imam Bonjol No. 40, Malang",
    tanggal: new Date("2024-05-15T09:20:00Z"),
    penyebab: "Lahir",
    tempat: "RS Saiful Anwar, Malang",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Sri Wahyuni",
    jenisKelaminPemohon: "P",
    noNikPemohon: "3472012345678915",
    alamatPemohon: "Jl. Diponegoro No. 25, Magelang",
    hubunganKeluargaPemohon: "Ibu",
    namaTerkait: "Bima Wahyudi",
    jenisKelaminTerkait: "L",
    noNikTerkait: "3472012345678916",
    alamatTerkait: "Jl. Diponegoro No. 25, Magelang",
    tanggal: new Date("2024-06-10T10:45:00Z"),
    penyebab: "Lahir",
    tempat: "RS Harapan, Magelang",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Dedi Rahmat",
    jenisKelaminPemohon: "L",
    noNikPemohon: "3173012345678917",
    alamatPemohon: "Jl. Pangeran Antasari No. 5, Jakarta",
    hubunganKeluargaPemohon: "Ayah",
    namaTerkait: "Siti Rahmat",
    jenisKelaminTerkait: "P",
    noNikTerkait: "3173012345678918",
    alamatTerkait: "Jl. Pangeran Antasari No. 5, Jakarta",
    tanggal: new Date("2024-07-22T13:15:00Z"),
    penyebab: "Lahir",
    tempat: "RS Fatmawati, Jakarta",
    status: "DIPROSES",
  },
  {
    namaPemohon: "Lina Hartati",
    jenisKelaminPemohon: "P",
    noNikPemohon: "3175012345678919",
    alamatPemohon: "Jl. Kebon Jeruk No. 19, Jakarta",
    hubunganKeluargaPemohon: "Ibu",
    namaTerkait: "Bayu Hartanto",
    jenisKelaminTerkait: "L",
    noNikTerkait: "3175012345678920",
    alamatTerkait: "Jl. Kebon Jeruk No. 19, Jakarta",
    tanggal: new Date("2024-08-05T08:30:00Z"),
    penyebab: "Lahir",
    tempat: "RS Siloam, Jakarta",
    status: "DIPROSES",
  },
];

export const dataSkBelumMenikah: z.infer<typeof skBelumMenikahSchema>[] = [
  {
    namaLengkap: "Andi Pratama",
    nik: "3172012345678901",
    tanggalLahir: new Date("1985-04-12T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Pegawai Negeri Sipil",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Sudirman No. 5, Jakarta",
  },
  {
    namaLengkap: "Budi Santoso",
    nik: "3374012345678902",
    tanggalLahir: new Date("1990-07-20T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Kristen",
    pekerjaan: "Wiraswasta",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Diponegoro No. 10, Bandung",
  },
  {
    namaLengkap: "Citra Dewi",
    nik: "3578012345678903",
    tanggalLahir: new Date("1995-11-15T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Hindu",
    pekerjaan: "Guru",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Kuta No. 8, Denpasar",
  },
  {
    namaLengkap: "Dewi Lestari",
    nik: "3279012345678904",
    tanggalLahir: new Date("1988-02-05T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Islam",
    pekerjaan: "Dokter",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Kartini No. 22, Surabaya",
  },
  {
    namaLengkap: "Eka Wijaya",
    nik: "3173012345678905",
    tanggalLahir: new Date("1983-09-25T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Buddha",
    pekerjaan: "Pengusaha",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Merdeka No. 3, Medan",
  },
  {
    namaLengkap: "Fajar Hidayat",
    nik: "3372012345678906",
    tanggalLahir: new Date("1978-06-10T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Petani",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Merbabu No. 12, Semarang",
  },
  {
    namaLengkap: "Gita Ayu",
    nik: "3476012345678907",
    tanggalLahir: new Date("1992-12-05T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Katolik",
    pekerjaan: "Perawat",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Malioboro No. 9, Yogyakarta",
  },
  {
    namaLengkap: "Herman Susanto",
    nik: "3278012345678908",
    tanggalLahir: new Date("1986-03-18T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Karyawan Swasta",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Ahmad Yani No. 15, Bogor",
  },
  {
    namaLengkap: "Ika Sari",
    nik: "3579012345678909",
    tanggalLahir: new Date("1997-08-22T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Kristen",
    pekerjaan: "Mahasiswa",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Gajah Mada No. 27, Malang",
  },
  {
    namaLengkap: "Joko Widodo",
    nik: "3176012345678910",
    tanggalLahir: new Date("1980-11-30T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Pedagang",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Kebon Jeruk No. 20, Jakarta",
  },
];

export const dataSkIjinKeramaian: z.infer<typeof skIjinKeramaianSchema>[] = [
  {
    nama: "Siti Nurhaliza",
    nik: "3172012345678911",
    tempatLahir: "Jakarta",
    tanggalLahir: new Date("1990-05-12T00:00:00Z"),
    alamat: "Jl. M.H. Thamrin No. 25, Jakarta",
    waktu: new Date("2024-09-15T09:00:00Z"),
    maksud: "Mengurus dokumen kependudukan",
    acara: "Konsultasi",
  },
  {
    nama: "Rahmat Hidayat",
    nik: "3373012345678912",
    tempatLahir: "Semarang",
    tanggalLahir: new Date("1985-03-22T00:00:00Z"),
    alamat: "Jl. Pemuda No. 18, Semarang",
    waktu: new Date("2024-08-20T10:30:00Z"),
    maksud: "Mengajukan perpanjangan KTP",
    acara: "Pengajuan",
  },
  {
    nama: "Dewi Sartika",
    nik: "3578012345678913",
    tempatLahir: "Surabaya",
    tanggalLahir: new Date("1993-07-18T00:00:00Z"),
    alamat: "Jl. Gubeng No. 10, Surabaya",
    waktu: new Date("2024-10-05T11:00:00Z"),
    maksud: "Pembuatan akta kelahiran",
    acara: "Pendaftaran",
  },
  {
    nama: "Andi Saputra",
    nik: "3279012345678914",
    tempatLahir: "Bandung",
    tanggalLahir: new Date("1980-12-10T00:00:00Z"),
    alamat: "Jl. Asia Afrika No. 30, Bandung",
    waktu: new Date("2024-11-01T14:00:00Z"),
    maksud: "Pengambilan surat pindah",
    acara: "Pengambilan Dokumen",
  },
  {
    nama: "Lina Kusuma",
    nik: "3173012345678915",
    tempatLahir: "Medan",
    tanggalLahir: new Date("1988-04-05T00:00:00Z"),
    alamat: "Jl. Sudirman No. 50, Medan",
    waktu: new Date("2024-12-20T15:30:00Z"),
    maksud: "Pendaftaran pernikahan",
    acara: "Pendaftaran",
  },
  {
    nama: "Budi Setiawan",
    nik: "3172012345678916",
    tempatLahir: "Yogyakarta",
    tanggalLahir: new Date("1979-02-14T00:00:00Z"),
    alamat: "Jl. Jendral Sudirman No. 45, Yogyakarta",
    waktu: new Date("2024-10-10T08:00:00Z"),
    maksud: "Permohonan perubahan alamat",
    acara: "Pengajuan",
  },
  {
    nama: "Rina Wulandari",
    nik: "3374012345678917",
    tempatLahir: "Bandung",
    tanggalLahir: new Date("1991-09-30T00:00:00Z"),
    alamat: "Jl. Merdeka No. 7, Bandung",
    waktu: new Date("2024-11-15T13:00:00Z"),
    maksud: "Pembuatan KTP baru",
    acara: "Pendaftaran",
  },
  {
    nama: "Heri Prasetyo",
    nik: "3578012345678918",
    tempatLahir: "Makassar",
    tanggalLahir: new Date("1984-06-25T00:00:00Z"),
    alamat: "Jl. Haji Bau No. 20, Makassar",
    waktu: new Date("2024-12-05T10:15:00Z"),
    maksud: "Pencatatan status pernikahan",
    acara: "Pendaftaran",
  },
  {
    nama: "Ayu Rahayu",
    nik: "3278012345678919",
    tempatLahir: "Medan",
    tanggalLahir: new Date("1996-11-12T00:00:00Z"),
    alamat: "Jl. A. Yani No. 32, Medan",
    waktu: new Date("2024-09-25T11:45:00Z"),
    maksud: "Pengurusan akta kematian",
    acara: "Pengajuan",
  },
  {
    nama: "Eko Susanto",
    nik: "3173012345678920",
    tempatLahir: "Palembang",
    tanggalLahir: new Date("1975-07-30T00:00:00Z"),
    alamat: "Jl. Sudirman No. 12, Palembang",
    waktu: new Date("2024-08-15T14:30:00Z"),
    maksud: "Pendaftaran anak baru lahir",
    acara: "Pendaftaran",
  },
];

export const dataSkPenghasilanOrangTua: z.infer<
  typeof skPenghasilanOrangTuaSchema
>[] = [
  {
    namaLengkap: "Maya Sari",
    nik: "3172012345678921",
    tanggalLahir: new Date("1982-03-14T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Islam",
    pekerjaan: "Arsitek",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Setiabudi No. 45, Jakarta",
    penghasilan: 120000000,
  },
  {
    namaLengkap: "Rudi Hartono",
    nik: "3374012345678922",
    tanggalLahir: new Date("1989-10-22T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Kristen",
    pekerjaan: "Manager",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Guntur No. 5, Bandung",
    penghasilan: 150000000,
  },
  {
    namaLengkap: "Sari Wulandari",
    nik: "3578012345678923",
    tanggalLahir: new Date("1990-07-15T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Hindu",
    pekerjaan: "Dokter",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Kamboja No. 7, Denpasar",
    penghasilan: 200000000,
  },
  {
    namaLengkap: "Johan Prabowo",
    nik: "3279012345678924",
    tanggalLahir: new Date("1975-12-05T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Pengacara",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Diponegoro No. 25, Semarang",
    penghasilan: 180000000,
  },
  {
    namaLengkap: "Nina Putri",
    nik: "3173012345678925",
    tanggalLahir: new Date("1988-08-30T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Buddha",
    pekerjaan: "Guru",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Raya No. 10, Surabaya",
    penghasilan: 90000000,
  },
  {
    namaLengkap: "Faisal Alim",
    nik: "3172012345678926",
    tanggalLahir: new Date("1984-01-20T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Sales Manager",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Panglima Polim No. 18, Jakarta",
    penghasilan: 130000000,
  },
  {
    namaLengkap: "Tina Mariana",
    nik: "3374012345678927",
    tanggalLahir: new Date("1994-04-28T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Kristen",
    pekerjaan: "Desainer Grafis",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Merdeka No. 8, Bali",
    penghasilan: 80000000,
  },
  {
    namaLengkap: "Hadi Susanto",
    nik: "3578012345678928",
    tanggalLahir: new Date("1980-11-11T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Programmer",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Gunung Agung No. 12, Yogyakarta",
    penghasilan: 140000000,
  },
  {
    namaLengkap: "Citra Dewi",
    nik: "3279012345678929",
    tanggalLahir: new Date("1992-05-10T00:00:00Z"),
    jenisKelamin: "P",
    agama: "Hindu",
    pekerjaan: "Penulis",
    statusPerkawinan: "BELUM_KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Pantai Kuta No. 15, Bali",
    penghasilan: 70000000,
  },
  {
    namaLengkap: "Rendi Saputra",
    nik: "3173012345678930",
    tanggalLahir: new Date("1987-07-30T00:00:00Z"),
    jenisKelamin: "L",
    agama: "Islam",
    pekerjaan: "Pengusaha",
    statusPerkawinan: "KAWIN",
    kewarganegaraan: "Indonesia",
    alamat: "Jl. Raya Bogor No. 20, Bogor",
    penghasilan: 250000000,
  },
];
